"use client";
import Image from "next/image";
import Link from "next/link";
import {useEffect,useState} from "react";
type Item={id:string;quantity:number;product:{name:string;slug:string;price:string|number;images:{url:string;altText:string|null}[]};variant?:{name:string;price:string|number|null;inventory?:{available:number}|null}|null};
const money=(v:unknown)=>Number(v).toLocaleString("en-BD",{maximumFractionDigits:2});
export function GuestCart(){
 const [items,setItems]=useState<Item[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState<string|null>(null),[error,setError]=useState("");
 async function load(){setLoading(true);try{const r=await fetch("/api/cart",{cache:"no-store"});const b=await r.json();if(!r.ok)throw new Error(b?.error||"Unable to load cart");setItems(b.items||[])}catch(e){setError(e instanceof Error?e.message:"Unable to load cart")}finally{setLoading(false)}}
 useEffect(()=>{
  // eslint-disable-next-line react-hooks/set-state-in-effect
  void load();
},[]);
 async function change(id:string,quantity:number){if(quantity<1)return;setBusy(id);setError("");try{const r=await fetch("/api/cart/items/"+id,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({quantity})});const b=await r.json().catch(()=>null);if(!r.ok)throw new Error(b?.error||"Unable to update cart");await load()}catch(e){setError(e instanceof Error?e.message:"Unable to update cart")}finally{setBusy(null)}}
 async function remove(id:string){setBusy(id);setError("");try{const r=await fetch("/api/cart/items/"+id,{method:"DELETE"});if(!r.ok)throw new Error("Unable to remove item");setItems(x=>x.filter(i=>i.id!==id))}catch(e){setError(e instanceof Error?e.message:"Unable to remove item")}finally{setBusy(null)}}
 if(loading)return <div className="mt-8 rounded-2xl border p-8 text-center text-sm text-slate-500">Loading your cart…</div>;
 if(error&&!items.length)return <div role="alert" className="mt-8 rounded-2xl bg-red-50 p-5 text-sm text-red-700">{error}</div>;
 if(!items.length)return <div className="mt-8 rounded-2xl border border-dashed p-12 text-center"><p className="text-slate-600">Your cart is empty.</p><Link href="/shop" className="mt-5 inline-flex rounded-xl bg-indigo-600 px-4 py-2 text-sm font-semibold text-white">Continue shopping</Link></div>;
 const subtotal=items.reduce((s,i)=>s+Number(i.variant?.price??i.product.price)*i.quantity,0);
 return <div className="mt-7 grid gap-6 lg:grid-cols-[1fr_340px]"><div className="space-y-3">{error?<p role="alert" className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>:null}{items.map(i=>{const price=Number(i.variant?.price??i.product.price);return <article key={i.id} className="flex gap-4 rounded-2xl border bg-white p-3 sm:p-4"><div className="relative h-24 w-24 shrink-0 overflow-hidden rounded-xl bg-slate-100">{i.product.images[0]?<Image src={i.product.images[0].url} alt={i.product.images[0].altText||i.product.name} fill sizes="96px" className="object-cover"/>:null}</div><div className="min-w-0 flex-1"><Link href={"/product/"+i.product.slug} className="font-semibold hover:text-indigo-600">{i.product.name}</Link>{i.variant?<p className="mt-1 text-xs text-slate-500">{i.variant.name}</p>:null}<p className="mt-2 font-semibold">৳{money(price)}</p><div className="mt-3 flex items-center gap-2"><button type="button" disabled={!!busy} onClick={()=>change(i.id,i.quantity-1)} className="h-9 w-9 rounded-lg border disabled:opacity-50">−</button><span className="w-7 text-center text-sm font-semibold">{i.quantity}</span><button type="button" disabled={!!busy} onClick={()=>change(i.id,i.quantity+1)} className="h-9 w-9 rounded-lg border disabled:opacity-50">+</button><button type="button" disabled={busy===i.id} onClick={()=>remove(i.id)} className="ml-2 text-xs font-semibold text-red-600 disabled:opacity-50">{busy===i.id?"Removing…":"Remove"}</button></div></div><div className="hidden text-right text-sm font-bold sm:block">৳{money(price*i.quantity)}</div></article>})}</div><aside className="h-fit rounded-2xl border bg-white p-5 lg:sticky lg:top-24"><h2 className="font-semibold">Order summary</h2><div className="mt-5 flex justify-between text-sm"><span>Subtotal</span><span>৳{money(subtotal)}</span></div><p className="mt-2 text-xs text-slate-500">Delivery fee is calculated securely at checkout.</p><div className="mt-4 border-t pt-4 flex justify-between text-lg font-bold"><span>Total</span><span>৳{money(subtotal)}</span></div><Link href="/checkout" className="mt-5 flex min-h-11 items-center justify-center rounded-xl bg-indigo-600 px-4 text-sm font-semibold text-white">Proceed to checkout</Link></aside></div>;
}