import type {PaymentProvider,PaymentResult} from "./contracts";
import {Prisma} from "@prisma/client";
const base=()=>process.env.SSLCOMMERZ_LIVE==="true"?"https://securepay.sslcommerz.com":"https://sandbox-gw.sslcommerz.com";
const validatorBase=()=>process.env.SSLCOMMERZ_LIVE==="true"?"https://securepay.sslcommerz.com":"https://sandbox.sslcommerz.com";
function req(name:string){const v=process.env[name];if(!v)throw new Error(`Missing ${name} configuration.`);return v;}
export class SSLCommerzProvider implements PaymentProvider{
 readonly name="SSLCOMMERZ";
 async createPayment(input:{orderId:string;amount:string;currency:"BDT";customerPhone:string;customerName:string;customerEmail:string;customerAddress:string;productCategory:string;returnUrl:string;cancelUrl:string}):Promise<PaymentResult>{
  const amount=new Prisma.Decimal(input.amount);if(amount.lt(10)||amount.gt(500000))throw new Error("Online payment amount must be between ৳10 and ৳500,000.");
  const tranId=input.orderId.slice(0,30);
  const form=new URLSearchParams({store_id:req("SSLCOMMERZ_STORE_ID"),store_passwd:req("SSLCOMMERZ_STORE_PASSWORD"),total_amount:amount.toFixed(2),currency:"BDT",tran_id:tranId,success_url:input.returnUrl,fail_url:input.cancelUrl,cancel_url:input.cancelUrl,ipn_url:input.returnUrl.replace(/\/payment\/callback\/?$/,"/api/payments/sslcommerz/ipn"),product_category:input.productCategory.slice(0,50),cus_name:input.customerName.slice(0,100),cus_email:input.customerEmail.slice(0,100),cus_phone:input.customerPhone.slice(0,20),cus_add1:input.customerAddress.slice(0,200),cus_city:"Dhaka",cus_country:"Bangladesh",shipping_method:"NO",product_name:"Zelux order",product_profile:"general"});
  const res=await fetch(`${base()}/gwprocess/v4/api.php`,{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body:form.toString(),cache:"no-store"});
  const data=await res.json().catch(()=>({}));if(!res.ok||data?.status!=="SUCCESS"||!data?.GatewayPageURL)throw new Error(data?.failedreason||data?.failedreason||"Unable to start online payment.");
  return {provider:this.name,providerReference:tranId,status:"PENDING",gatewayUrl:String(data.GatewayPageURL)};
 }
 async refundPayment(providerReference:string,amount:string,remarks:string){const q=new URLSearchParams({tran_id:providerReference,store_id:req("SSLCOMMERZ_STORE_ID"),store_passwd:req("SSLCOMMERZ_STORE_PASSWORD"),format:"json"});const qr=await fetch(`${validatorBase()}/validator/api/merchantTransIDvalidationAPI.php?${q}`,{cache:"no-store"});const qd=await qr.json().catch(()=>({}));const element=(qd?.element||[]).find((x:any)=>["VALID","VALIDATED"].includes(String(x?.status))&&x?.bank_tran_id);if(!qr.ok||!element)throw new Error("No completed bank transaction was found for refund.");const refundId=`ZLX-R-${Date.now().toString(36).toUpperCase()}`;const params=new URLSearchParams({bank_tran_id:String(element.bank_tran_id),refund_trans_id:refundId,refe_id:refundId,refund_amount:new Prisma.Decimal(amount).toFixed(2),refund_remarks:remarks.slice(0,255),store_id:req("SSLCOMMERZ_STORE_ID"),store_passwd:req("SSLCOMMERZ_STORE_PASSWORD"),format:"json"});const rr=await fetch(`${validatorBase()}/validator/api/merchantTransIDvalidationAPI.php?${params}`,{cache:"no-store"});const rd=await rr.json().catch(()=>({}));if(!rr.ok||!["success","processing"].includes(String(rd?.status)))throw new Error(rd?.errorReason||"Unable to initiate refund.");return{status:String(rd.status) as "success"|"processing",refundReference:rd.refund_ref_id};}
 async queryRefund(refundReference:string){const params=new URLSearchParams({refund_ref_id:refundReference,store_id:req("SSLCOMMERZ_STORE_ID"),store_passwd:req("SSLCOMMERZ_STORE_PASSWORD"),format:"json"});const r=await fetch(`${validatorBase()}/validator/api/merchantTransIDvalidationAPI.php?${params}`,{cache:"no-store"});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error("Unable to query refund status.");const status=String(d?.status||"processing").toLowerCase();if(!["refunded","processing","cancelled"].includes(status))throw new Error("Unknown refund status.");return{status:status as "refunded"|"processing"|"cancelled",refundReference:String(d?.refund_ref_id||refundReference)};}
 async verifyPayment(providerReference:string){
  const params=new URLSearchParams({tran_id:providerReference,store_id:req("SSLCOMMERZ_STORE_ID"),store_passwd:req("SSLCOMMERZ_STORE_PASSWORD"),format:"json"});
  const res=await fetch(`${validatorBase()}/validator/api/merchantTransIDvalidationAPI.php?${params}`,{cache:"no-store"});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error("Unable to query payment status.");
  const elements=Array.isArray(data?.element)?data.element:[];const match=elements.find((x:any)=>String(x?.tran_id)===providerReference)||elements[0];const rawStatus=String(match?.status||data?.status||"PENDING").toUpperCase();const status: PaymentResult["status"]=rawStatus==="VALID"||rawStatus==="VALIDATED"?"PAID":rawStatus==="FAILED"?"FAILED":"PENDING";return{provider:this.name,providerReference,status,amount:match?.currency_type==="BDT"?String(match?.amount||match?.currency_amount||""):String(match?.amount||"")};
 }
}