"use client";
import {useState} from "react";
import {Button} from "@/components/ui/button";
type Shipment={id:string;order:{id:string;orderNumber:string;status:string};provider:string|null;trackingId:string|null;status:string};
export function AdminShippingTable({shipments}:{shipments:Shipment[]}){
 const [busy,setBusy]=useState<string|null>(null);
 async function action(orderId:string,kind:"book"|"reconcile"){setBusy(orderId+kind);const url=kind==="book"?`/api/admin/orders/${orderId}/shipment`:"/api/admin/shipping/reconcile";const r=await fetch(url,{method:"POST",headers:{"content-type":"application/json"},body:kind==="reconcile"?JSON.stringify({orderId}):undefined});if(!r.ok){const body=await r.json().catch(()=>null);alert(body?.error||"Courier operation failed.");setBusy(null);return}location.reload()}
 return <div className="overflow-x-auto rounded-2xl border bg-white"><table className="w-full min-w-[900px] text-left text-sm"><thead><tr>{["Order","Provider","Tracking","Shipment","Order status","Action"].map(x=><th key={x} className="px-4 py-3">{x}</th>)}</tr></thead><tbody>{shipments.map(s=><tr key={s.id} className="border-t"><td className="px-4 py-4"><a className="text-indigo-600" href={"/admin/orders/"+s.order.id}>{s.order.orderNumber}</a></td><td className="px-4 py-4">{s.provider||"—"}</td><td className="px-4 py-4 font-mono text-xs">{s.trackingId||"—"}</td><td className="px-4 py-4">{s.status}</td><td className="px-4 py-4">{s.order.status}</td><td className="px-4 py-4">{s.trackingId&&s.status!=="DELIVERED"&&s.status!=="CANCELLED"?<Button size="sm" variant="outline" disabled={!!busy} onClick={()=>void action(s.order.id,"reconcile")}>{busy===s.order.id+"reconcile"?"Checking…":"Refresh"}</Button>:s.order.status==="READY_TO_SHIP"&&!s.trackingId?<Button size="sm" disabled={!!busy} onClick={()=>void action(s.order.id,"book")}>{busy===s.order.id+"book"?"Booking…":"Book courier"}</Button>:<span className="text-slate-400">—</span>}</td></tr>)}</tbody></table></div>
}
