"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";

export function ProductForm({product}:{product?:any}){
 const router=useRouter();
 const [busy,setBusy]=useState(false),[error,setError]=useState("");
 const [form,setForm]=useState({name:product?.name??"",slug:product?.slug??"",sku:product?.sku??"",description:product?.description??"",shortDescription:product?.shortDescription??"",brand:product?.brand??"",price:String(product?.price??""),compareAtPrice:product?.compareAtPrice==null?"":String(product.compareAtPrice),costPrice:product?.costPrice==null?"":String(product.costPrice),weightGrams:product?.weightGrams==null?"":String(product.weightGrams),isPublished:product?.isPublished??false,isFeatured:product?.isFeatured??false});
 const [images,setImages]=useState<any[]>((product?.images??[]).map((x:any)=>({id:x.id,url:x.url,altText:x.altText??""})));
 const [variants,setVariants]=useState<any[]>((product?.variants??[]).map((x:any)=>({id:x.id,sku:x.sku,name:x.name,attributes:JSON.stringify(x.attributes??{}),price:x.price==null?"":String(x.price),available:String(x.inventory?.available??0),lowStockThreshold:String(x.inventory?.lowStockThreshold??5)})));
 const set=(k:string,v:any)=>setForm(x=>({...x,[k]:v}));
 const save=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError("");try{
  const payload:any={...form,price:Number(form.price),compareAtPrice:form.compareAtPrice===""?null:Number(form.compareAtPrice),costPrice:form.costPrice===""?null:Number(form.costPrice),weightGrams:form.weightGrams===""?null:Number(form.weightGrams)};
  if(product){payload.images=images.filter(x=>x.url.trim()).map((x,i)=>({...x,sortOrder:i}));payload.variants=variants.map(x=>{let attributes={};try{attributes=x.attributes?JSON.parse(x.attributes):{}}catch{throw new Error("Variant attributes must be valid JSON.")}return {...x,price:x.price===""?null:Number(x.price),available:Number(x.available),lowStockThreshold:Number(x.lowStockThreshold),attributes};});}
  const r=await fetch(product?"/api/admin/products/"+product.id:"/api/admin/products",{method:product?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const d=await r.json().catch(()=>null);if(!r.ok)throw new Error(d?.error||"Unable to save product");router.push(product?"/admin/products/"+product.id+"/edit":"/admin/products");router.refresh();
 }catch(e){setError(e instanceof Error?e.message:"Unable to save product");setBusy(false)}};
 const field=(k:string,label:string,type="text")=><label className="text-sm font-medium">{label}<input required={["name","slug","sku","price"].includes(k)} value={(form as any)[k]} onChange={e=>set(k,e.target.value)} type={type} step="0.01" className="mt-1 w-full rounded-xl border px-3 py-2.5"/></label>;
 return <form onSubmit={save} className="grid gap-6 rounded-2xl border bg-white p-5">
  <div className="grid gap-4 sm:grid-cols-2">{field("name","Name")}{field("slug","Slug")}{field("sku","SKU")}{field("brand","Brand")}{field("price","Price","number")}{field("compareAtPrice","Compare at","number")}{field("costPrice","Cost","number")}{field("weightGrams","Weight (grams)","number")}</div>
  <label className="text-sm font-medium">Description<textarea required value={form.description} onChange={e=>set("description",e.target.value)} className="mt-1 min-h-32 w-full rounded-xl border p-3"/></label>
  <label className="text-sm font-medium">Short description<textarea value={form.shortDescription} onChange={e=>set("shortDescription",e.target.value)} className="mt-1 min-h-20 w-full rounded-xl border p-3"/></label>
  {product&&<><section><div className="mb-3 flex justify-between"><h2 className="font-bold">Images</h2><button type="button" onClick={()=>setImages(x=>[...x,{url:"",altText:""}])} className="rounded-lg border px-3 py-1.5 text-sm">Add image</button></div><div className="grid gap-3">{images.map((x,i)=><div key={x.id??i} className="grid gap-2 sm:grid-cols-[1fr_1fr_auto]"><input value={x.url} onChange={e=>setImages(a=>a.map((v,j)=>j===i?{...v,url:e.target.value}:v))} placeholder="https://image-url" className="rounded-xl border px-3 py-2"/><input value={x.altText} onChange={e=>setImages(a=>a.map((v,j)=>j===i?{...v,altText:e.target.value}:v))} placeholder="Alt text" className="rounded-xl border px-3 py-2"/><button type="button" onClick={()=>setImages(a=>a.filter((_,j)=>j!==i))} className="rounded-xl border px-3 py-2 text-red-600">Remove</button></div>)}</div></section>
  <section><div className="mb-3 flex justify-between"><h2 className="font-bold">Variants & stock</h2><button type="button" onClick={()=>setVariants(x=>[...x,{sku:"",name:"",attributes:"{}",price:"",available:"0",lowStockThreshold:"5"}])} className="rounded-lg border px-3 py-1.5 text-sm">Add variant</button></div><div className="grid gap-3">{variants.map((x,i)=><div key={x.id??i} className="grid gap-2 rounded-xl border p-3 sm:grid-cols-2 lg:grid-cols-3"><input value={x.name} onChange={e=>setVariants(a=>a.map((v,j)=>j===i?{...v,name:e.target.value}:v))} placeholder="Name" className="rounded-lg border px-3 py-2"/><input value={x.sku} onChange={e=>setVariants(a=>a.map((v,j)=>j===i?{...v,sku:e.target.value}:v))} placeholder="SKU" className="rounded-lg border px-3 py-2"/><input value={x.attributes} onChange={e=>setVariants(a=>a.map((v,j)=>j===i?{...v,attributes:e.target.value}:v))} placeholder='{"color":"Black"}' className="rounded-lg border px-3 py-2"/><input value={x.price} onChange={e=>setVariants(a=>a.map((v,j)=>j===i?{...v,price:e.target.value}:v))} placeholder="Price override" type="number" className="rounded-lg border px-3 py-2"/><input value={x.available} onChange={e=>setVariants(a=>a.map((v,j)=>j===i?{...v,available:e.target.value}:v))} placeholder="Stock" type="number" className="rounded-lg border px-3 py-2"/><input value={x.lowStockThreshold} onChange={e=>setVariants(a=>a.map((v,j)=>j===i?{...v,lowStockThreshold:e.target.value}:v))} placeholder="Low stock" type="number" className="rounded-lg border px-3 py-2"/><button type="button" onClick={()=>setVariants(a=>a.filter((_,j)=>j!==i))} className="rounded-lg border px-3 py-2 text-red-600">Remove variant</button></div>)}</div></section></>}
  <div className="flex flex-wrap gap-5"><label><input type="checkbox" checked={form.isPublished} onChange={e=>set("isPublished",e.target.checked)}/> <span className="ml-2">Published</span></label><label><input type="checkbox" checked={form.isFeatured} onChange={e=>set("isFeatured",e.target.checked)}/> <span className="ml-2">Featured</span></label></div>
  {error&&<p className="text-sm text-red-600">{error}</p>}<button disabled={busy} className="rounded-xl bg-indigo-600 px-5 py-3 font-semibold text-white disabled:opacity-50">{busy?"Saving…":"Save product"}</button>
 </form>
}