import type {Metadata} from "next";
import Link from "next/link";
import {db} from "@/lib/db/client";
export const metadata:Metadata={title:"Compare Products | Zelux",description:"Compare selected Zelux products side by side."};
const money=(v:unknown)=>Number(v).toLocaleString("en-BD",{maximumFractionDigits:2});
export default async function ComparePage({searchParams}:{searchParams:Promise<{ids?:string}>}){
 const raw=(await searchParams).ids||"";
 const ids=[...new Set(raw.split(",").map(x=>x.trim()).filter(Boolean))].slice(0,4);
 const products=ids.length?await db.product.findMany({where:{id:{in:ids},isPublished:true},include:{images:{orderBy:{sortOrder:"asc"},take:1},inventory:true,variants:true},take:4}):[];
 const byId=new Map(products.map(p=>[p.id,p])); const ordered=ids.map(id=>byId.get(id)).filter(Boolean);
 return <main className="mx-auto min-h-[70vh] max-w-7xl px-4 py-10"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-semibold text-indigo-600">Shopping tool</p><h1 className="mt-1 text-3xl font-bold">Compare Products</h1><p className="mt-2 text-slate-600">Compare up to four published products using their stored catalog information.</p></div><Link href="/shop" className="rounded-xl border bg-white px-4 py-2 text-sm font-semibold">Back to shop</Link></div>{ordered.length?<div className="mt-8 overflow-x-auto rounded-2xl border bg-white"><table className="min-w-[680px] w-full text-left text-sm"><thead><tr><th className="w-40 border-b p-4 text-slate-500">Specification</th>{ordered.map(p=><th key={p!.id} className="border-b p-4 align-top"><Link className="font-bold hover:text-indigo-600" href={"/product/"+p!.slug}>{p!.name}</Link></th>)}</tr></thead><tbody><tr><td className="border-b p-4 font-medium text-slate-500">Price</td>{ordered.map(p=><td key={p!.id} className="border-b p-4 font-bold">৳{money(p!.price)}</td>)}</tr><tr><td className="border-b p-4 font-medium text-slate-500">Brand</td>{ordered.map(p=><td key={p!.id} className="border-b p-4">{p!.brand||"Not specified"}</td>)}</tr><tr><td className="border-b p-4 font-medium text-slate-500">SKU</td>{ordered.map(p=><td key={p!.id} className="border-b p-4">{p!.sku}</td>)}</tr><tr><td className="border-b p-4 font-medium text-slate-500">Availability</td>{ordered.map(p=><td key={p!.id} className="border-b p-4">{(p!.inventory?.available??0)>0?"In stock":"Out of stock"}</td>)}</tr><tr><td className="p-4 font-medium text-slate-500">Variants</td>{ordered.map(p=><td key={p!.id} className="p-4">{p!.variants.length?p!.variants.length+" option"+(p!.variants.length===1?"":"s"):"None"}</td>)}</tr></tbody></table></div>:<div className="mt-8 rounded-2xl border border-dashed bg-white p-12 text-center text-slate-500">Select products from the catalog to compare. Add their IDs to the <code>ids</code> query parameter, up to four products.</div>}</main>;
}