"use client";
import Image from "next/image";import Link from "next/link";import {useEffect,useState} from "react";
type Product={id:string;name:string;slug:string;price:string|number;images:{id:string;url:string;altText:string|null}[];inventory:{available:number}|null};
export function ProductCollection({mode}:{mode:"recent"|"compare"}){
 const[key,setKey]=useState<string[]>([]);const[items,setItems]=useState<Product[]>([]);const[loading,setLoading]=useState(true);
 useEffect(()=>{try{const k=mode==="recent"?"zelux:recently-viewed":"zelux:compare";const ids=JSON.parse(localStorage.getItem(k)||"[]") as string[];setKey(ids);if(!ids.length){setLoading(false);return}fetch("/api/products/lookup?ids="+encodeURIComponent(ids.join(","))).then(r=>r.ok?r.json():[]).then((rows:Product[])=>setItems(rows)).catch(()=>setItems([])).finally(()=>setLoading(false));}catch{setLoading(false)}},[mode]);
 function clear(){localStorage.removeItem(mode==="recent"?"zelux:recently-viewed":"zelux:compare");setKey([]);setItems([])}
 if(loading)return <div className="mt-8 rounded-2xl border bg-white p-8 text-sm text-slate-500">Loading products…</div>;
 return <>{items.length?<><div className="mt-6 flex justify-end"><button onClick={clear} className="rounded-xl border px-3 py-2 text-sm font-medium hover:bg-slate-50">Clear all</button></div><div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">{items.map(p=><Link key={p.id} href={"/product/"+p.slug} className="rounded-2xl border bg-white p-3 transition hover:-translate-y-0.5 hover:shadow-sm"><div className="relative aspect-square overflow-hidden rounded-xl bg-slate-100">{p.images[0]?<Image src={p.images[0].url} alt={p.images[0].altText||p.name} fill sizes="25vw" className="object-cover"/>:null}</div><p className="mt-3 line-clamp-2 text-sm font-semibold">{p.name}</p><p className="mt-1 font-bold">৳{Number(p.price).toLocaleString("en-BD")}</p><p className={"mt-1 text-xs "+((p.inventory?.available??0)>0?"text-green-700":"text-red-600")}>{(p.inventory?.available??0)>0?"In stock":"Out of stock"}</p></Link>)}</div></>:<div className="mt-8 rounded-2xl border border-dashed p-10 text-center"><p className="font-medium">No products here yet.</p><p className="mt-1 text-sm text-slate-500">{mode==="recent"?"Products you view will appear here.":"Add products to compare from their product pages."}</p><Link href="/shop" className="mt-4 inline-block rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white">Browse shop</Link></div>}</>
}