import Link from "next/link";
import {listPublishedProducts} from "@/modules/products/service";
import {ProductCard} from "@/components/product/product-card";
export const metadata={title:"Shop | Zelux"};
export default async function ShopPage({searchParams}:{searchParams:Promise<{q?:string;sort?:string;page?:string}>}){
 const p=await searchParams;const page=Math.max(1,Number(p.page)||1);const take=24;
 const products=await listPublishedProducts({take,skip:(page-1)*take,q:p.q});
 const sorted=[...products].sort((a,b)=>p.sort==="price_asc"?Number(a.price)-Number(b.price):p.sort==="price_desc"?Number(b.price)-Number(a.price):0);
 const query=(n:number)=>{const x=new URLSearchParams();if(p.q)x.set("q",p.q);if(p.sort)x.set("sort",p.sort);x.set("page",String(n));return "/shop?"+x.toString()};
 return <main className="mx-auto min-h-[70vh] max-w-7xl px-4 py-8 sm:py-10"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-semibold text-indigo-600">Zelux Store</p><h1 className="mt-1 text-3xl font-bold tracking-tight">Shop</h1><p className="mt-2 text-sm text-slate-600">{products.length? "Showing "+(((page-1)*take)+1)+"–"+(((page-1)*take)+products.length):"No"} products</p></div><form className="flex w-full flex-wrap gap-2 sm:w-auto"><input name="q" defaultValue={p.q} placeholder="Search products" className="h-10 min-w-0 flex-1 rounded-lg border px-3 text-sm sm:w-56"/><select name="sort" defaultValue={p.sort||""} className="h-10 rounded-lg border px-3 text-sm"><option value="">Newest</option><option value="price_asc">Price: low to high</option><option value="price_desc">Price: high to low</option></select><button className="rounded-lg bg-indigo-600 px-4 text-sm font-semibold text-white">Apply</button></form></div>{sorted.length?<><div className="mt-7 grid grid-cols-2 gap-3 sm:grid-cols-3 sm:gap-5 lg:grid-cols-4">{sorted.map(p=><ProductCard key={p.id} product={p}/>)}</div><div className="mt-8 flex justify-center gap-2">{page>1?<Link href={query(page-1)} className="rounded-xl border px-4 py-2 text-sm font-semibold">Previous</Link>:null}{products.length===take?<Link href={query(page+1)} className="rounded-xl bg-indigo-600 px-4 py-2 text-sm font-semibold text-white">Next</Link>:null}</div></>:<div className="mt-8 rounded-2xl border border-dashed p-12 text-center text-slate-500">No products found.<div className="mt-4"><Link href="/shop" className="text-indigo-600">Clear filters</Link></div></div>}</main>;
}